load("C:/Users/pc/Downloads/HR_comma_sep.csv")
data<- read.csv("C:/Users/pc/Downloads/HR_comma_sep.csv")
dim(data)
summary(data)
str(data)
columns(is.na(data))
var(data$last_evaluation)
median(data$last_evaluation)
mode(data$last_evaluation)
min(data$last_evaluation)
max(data$last_evaluation)
quantile(data$last_evaluation)